@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.obscuria.aquamirae;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;